package View.Requests;

public enum SellerRequest{
    VIEW_COMPANY_INFORMATION,
    VIEW_SALES_HISTORY,
    MANAGE_PRODUCTS,
    SHOW_CATEGORIES,
    VIEW_SELLERS_SALES,
    VIEW_BALANCE,
    VIEW_PRODUCT_BUYERS,
    EDIT_PRODUCT,
    ADD_PRODUCT,
    VIEW_SALE,
    REMOVE_PRODUCT,
    EDIT_SALE,
    ADD_SALE,
    VIEW_SALE_HELP,
    GO_BACK,
    EDIT_SALE_HELP,
    EDIT_STARTING_DATE,
    EDIT_ENDING_DATE,
    ADD_PRODUCTS_TO_OFF,
    REMOVE_PRODUCTS_FROM_OFF,
    EDIT_SALES_OFF_PERCENT
}
